"""make user pw nullable

Revision ID: 39c4e44aa237
Revises: ee4faf55f684
Create Date: 2024-05-30 16:30:50.379579

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "39c4e44aa237"
down_revision = "ee4faf55f684"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "password", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "password", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
